### ISSUE TITLE
Scalar.AspNetcore Not loading Authenication types

### ISSUE THREAD

**Issue by juvegitau** [xC0dex/APIWeaver#140]
Below is the error on the browser inspection screen : 
hook.js:608 TypeError: Cannot read properties of undefined (reading 'uid')
    at Cye (scalar.js:27559:6)
    at scalar.js:27602:50
    at c (scalar.js:501:10)
    at Array.map (<anonymous>)
    at tn (scalar.js:502:40)
    at Proxy.map (scalar.js:488:8)
    at rr.fn (scalar.js:27602:42)
    at $t (scalar.js:432:49)
    at get value (scalar.js:608:9)
    at Proxy.<anonymous> (scalar.js:27609:34)

![image](https://github.com/user-attachments/assets/b3580cf1-a91e-40fa-a655-8e1cf52e287b)

**Comment by juvegitau** [comment]
not the right forum
